build-kernel-deb: Add generic config command
Signed-off-by: Juerg Haefliger <juergh@proton.me>

diff --git a/build-kernel-deb b/build-kernel-deb
--- a/build-kernel-deb
+++ b/build-kernel-deb
@@ -7,7 +7,7 @@ function run_chroot()
 {
 	echo "-- Run in chroot (${CHROOT}):"
 	echo "+ ${*}"
-	run-chroot "${CHROOT}" -- "${@}"
+	run-chroot cranky--"${CHROOT}" -- "${@}"
 }
 
 function usage()
@@ -17,33 +17,50 @@ Usage: $(basename "${0}") [-h] CMD [ARGS...]
 
 Build kernel Debian packages.
 
+To build an Ubuntu raspi kernel:
+  $ build-kernel-deb config raspi
+  $ build-kernel-deb make
+
+To build a generic Ubuntu kernel:
+  $ build-kernel-deb config generic
+  $ build-kernel-deb make
+
 Available commands:
+  config CONFIG    Generate .config for the build.
   make             Build kernel Debian packages.
   menuconfig       Run config menu.
+                   This is an alias for 'config menu'.
   ubuntuconfig     Use generic Ubuntu config.
+                   This is an alias for 'config ubuntu'.
 
 Optional arguments:
   --arch ARCH      Debian package architecture.
-  --chroot CHROOT  Use chroot CHROOT.
+  --buildd BUILDD  Use buildd/<BUILDD> as the build output directory.
+                   If not provided, defaults to buildd/<SERIES>.
+  --chroot CHROOT  Use chroot <CHROOT>.
   -h, --help       Show this help text and exit.
   -jX              Number of jobs, default one per CPU.
-
-Optional arguments for 'ubuntuconfig':
-  --lsmod LSMOD    Build only modules listed in LSMOD.
+  --lsmod LSMOD    Build only modules listed in <LSMOD>.
 EOF
 }
 
 arch=
+buildd=
 chroot=
 jobs=$(getconf _NPROCESSORS_ONLN)
 lsmod=
 cmd=
+flavor=
 
 while [ ${#} -gt 0 ] ; do
 	case "${1}" in
 		--arch)
 			shift
 			arch=${1}
+			;;
+		--buildd)
+			shift
+			buildd=${1}
 			;;
 		--chroot)
 			shift
@@ -64,7 +81,16 @@ while [ ${#} -gt 0 ] ; do
 			shift
 			lsmod=${1}
 			;;
-		make|menuconfig|ubuntuconfig)
+		config)
+			cmd=${1}
+			shift
+			flavor=${1}
+			;;
+		*config)
+			cmd=config
+			flavor=${1%config}
+			;;
+		make)
 			cmd=${1}
 			;;
 		*)
@@ -117,7 +143,12 @@ fi
 # Set exports
 #
 
-KBUILD_OUTPUT=buildd/${series}
+if [ -n "${buildd}" ] ; then
+	KBUILD_OUTPUT=buildd/${buildd}
+else
+	KBUILD_OUTPUT=buildd/${series}
+fi
+mkdir -p "${KBUILD_OUTPUT}"
 
 echo "-- Use kernel build output directory: ${KBUILD_OUTPUT}"
 export KBUILD_OUTPUT
@@ -127,34 +158,46 @@ export KBUILD_OUTPUT
 #
 
 case "${cmd}" in
-	ubuntuconfig)
-		echo "-- Generate Ubuntu config"
-		rm -rf CONFIGS
-		run_chroot fakeroot debian/rules clean
-		run_chroot debian/rules genconfigs || true
+	config)
+		case "${flavor}" in
+			menu)
+				run_chroot make menuconfig
+				;;
 
-		mkdir -p "${KBUILD_OUTPUT}"
-		cp CONFIGS/"${arch}"-config.flavour.generic "${KBUILD_OUTPUT}"/.config
+			ubuntu|raspi|generic)
+				if [ "${flavor}" = ubuntu ] ; then
+					flavor=generic
+				fi
 
-		# Disable CONFIG_DEBUG_INFO
-		sed -i '/CONFIG_DEBUG_INFO/d' "${KBUILD_OUTPUT}"/.config
-		echo "# CONFIG_DEBUG_INFO is not set" >> "${KBUILD_OUTPUT}"/.config
+				echo "-- Generate Ubuntu config (${arch}, ${flavor})"
+				rm -rf CONFIGS
+				run_chroot fakeroot debian/rules clean
+				run_chroot debian/rules genconfigs || true
 
-		if [ -e "${lsmod}" ] ; then
-			echo
-			echo "-- Enable only local modules"
-			run_chroot make LSMOD="$(realpath -e "${lsmod}")" localmodconfig
-		else
-			run_chroot make olddefconfig
-		fi
+				cp CONFIGS/"${arch}"-config.flavour."${flavor}" "${KBUILD_OUTPUT}"/.config
+
+				# Disable CONFIG_DEBUG_INFO
+				sed -i '/CONFIG_DEBUG_INFO/d' "${KBUILD_OUTPUT}"/.config
+				echo "# CONFIG_DEBUG_INFO is not set" >> "${KBUILD_OUTPUT}"/.config
+
+				if [ -e "${lsmod}" ] ; then
+					echo
+					echo "-- Enable only local modules"
+					run_chroot make LSMOD="$(realpath -e "${lsmod}")" localmodconfig
+				else
+					run_chroot make olddefconfig
+				fi
+				;;
+
+			*)
+				echo "Invalid config type: ${flavor}" >&2
+				exit 1
+				;;
+		esac
 		;;
 
 	make)
 		run_chroot make -j"${jobs}" "${@:-bindeb-pkg}"
-		;;
-
-	menuconfig)
-		run_chroot make menuconfig
 		;;
 
 	*)
