cranky-{build,review}-sources: Add OFFSET commandline option
Signed-off-by: Juerg Haefliger <juergh@gmail.com>

diff --git a/cranky-build-sources b/cranky-build-sources
--- a/cranky-build-sources
+++ b/cranky-build-sources
@@ -16,14 +16,14 @@ function out()
 function usage()
 {
 	cat <<EOF
-Usage: cranky-build-sources [-c] [-f] [-h] [-n] [-o] POCKET
+Usage: cranky-build-sources [-c] [-f] [-h] [-n] [-o] POCKET|OFFSET
 
 Build a set of kernel packages.
 
 Positional arguments:
-  POCKET       The pocket to get the versions of the previous kernel packages
-               from. If set to 'none', uses the version from the previous
-               changelog entries.
+  POCKET       Get the previous package versions from pocket POCKET.
+  OFFSET       Get the previous package versions from the changelogs using
+               changelog entry offset OFFSET (1 == previous changelog entry).
 
 Optional arguments:
   -c, --current  Only build the source package for the current directory.
@@ -37,6 +37,7 @@ EOF
 current=0
 force=0
 pocket=
+offset=
 build_opts=()
 
 bo_meta=()
@@ -63,13 +64,19 @@ while [ "${#}" -gt 0 ] ; do
 		-o|--orig)
 			bo_main+=("-sa")
 			;;
-		updates|release|security|proposed|none)
-			if [ -z "${pocket}" ] ; then
-				pocket=${1}
-			else
+		updates|release|security|proposed)
+			if [ -n "${pocket}" ] ; then
 				echo "Invalid argument: ${1}" >&2
 				exit 2
 			fi
+			pocket=${1}
+			;;
+		[1-9])
+			if [ -n "${offset}" ] ; then
+				echo "Invalid argument: ${1}" >&2
+				exit 2
+			fi
+			offset=${1}
 			;;
 		*)
 			echo "Invalid argument: ${1}" >&2
@@ -79,7 +86,7 @@ while [ "${#}" -gt 0 ] ; do
 	shift
 done
 
-if [ -z "${pocket}" ] ; then
+if [ -z "${pocket}" ] && [ -z "${offset}" ] ; then
 	usage
 	exit 2
 fi
@@ -109,13 +116,13 @@ if [ "${force}" -eq 0 ] ; then
 	fi
 fi
 
-if [ "${pocket}" = "none" ] ; then
-	# Use the previous package versions
+if [ -n "${offset}" ] ; then
+	# Use the package version from the changelog
 	while IFS= read -r path ; do
-		package=$(dpkg-parsechangelog -l "${path}"/debian/changelog -o 1 -c 1 \
-									  -S source)
-		version=$(dpkg-parsechangelog -l "${path}"/debian/changelog -o 1 -c 1 \
-									  -S version)
+		package=$(dpkg-parsechangelog -l "${path}"/debian/changelog \
+									  -o "${offset}" -c 1 -S source)
+		version=$(dpkg-parsechangelog -l "${path}"/debian/changelog \
+									  -o "${offset}" -c 1 -S version)
 		case "${package}" in
 			linux-meta*)
 				bo_meta+=("-v${version}")
@@ -135,7 +142,7 @@ if [ "${pocket}" = "none" ] ; then
 		esac
 	done < <(cranky shell-helper source-packages-path)
 
-elif [ "${pocket}" != "none" ] ; then
+else
 	# Get the previous versions from the provided pocket
 	found=0
 	while IFS=' ' read -r package version rest ; do
diff --git a/cranky-review-sources b/cranky-review-sources
--- a/cranky-review-sources
+++ b/cranky-review-sources
@@ -62,7 +62,7 @@ function review_src()
 		return
 	fi
 
-	if [ -z "${POCKET}" ] && [ -z "${VERSION}" ] ; then
+	if [ -z "${POCKET}" ] && [ -z "${OFFSET}" ] ; then
 		# Review an existing debdiff
 		if ! [ -e ../"${debdiff}" ] ; then
 			echo "No .debdiff file found: ${debdiff}" >&2
@@ -100,11 +100,9 @@ function review_src()
 		fi
 
 		# Figure out the previous package version
-		if [ -n "${VERSION}" ] ; then
-			prev_version=${VERSION}
-		elif [ "${POCKET}" = "none" ] ; then
+		if [ -n "${OFFSET}" ] ; then
 			prev_version=$(dpkg-parsechangelog -l "${DEBIAN}"/changelog \
-											   -S Version -o 1 -c 1)
+											   -o "${OFFSET}" -c 1 -S Version)
 		else
 			prev_version=${PREV_VERSION[${src}]}
 		fi
@@ -139,18 +137,17 @@ function review_src()
 function usage()
 {
 	cat <<EOF
-Usage: cranky review-sources [-c] [-h] [POCKET|VERSION]
+Usage: cranky review-sources [-c] [-h] [POCKET|OFFSET]
 
 Review the differences between the current kernel source packages and
 previous source packages.
 
 Positional arguments:
-  POCKET         The name of the pocket that contains the previous kernel
-                 packages to compare against. If set to 'none', uses the
-                 version from the previous changelog entry.
-  VERSION        The version of the previous dsc file to compare against.
+  POCKET         Get the previous package versions from pocket POCKET.
+  OFFSET         Get the previous package versions from the changelogs using
+                 changelog entry offset OFFSET (1 == previous changelog entry).
 
-  If neither POCKET nor VERSION is provided, process the existing debdiff.
+  If neither POCKET nor OFFSET is provided, process the existing debdiff.
 
 Optional arguments:
   -c, --current  Only review the source package built from the current
@@ -161,7 +158,7 @@ EOF
 
 current=0
 POCKET=
-VERSION=
+OFFSET=
 
 while [ ${#} -gt 0 ] ; do
 	case "${1}" in
@@ -172,19 +169,23 @@ while [ ${#} -gt 0 ] ; do
 			usage
 			exit
 			;;
-		*)
-			if [ -n "${POCKET}" ] || [ -n "${VERSION}" ] ; then
+		release|security|updates|proposed)
+			if [ -n "${POCKET}" ] ; then
 				echo "Invalid argument: ${1}" >&2
 				exit 2
 			fi
-			case "${1}" in
-				release|security|updates|proposed|none)
-					POCKET=${1}
-					;;
-				*)
-					VERSION=${1}
-					;;
-			esac
+			POCKET=${1}
+			;;
+		[1-9])
+			if [ -n "${OFFSET}" ] ; then
+				echo "Invalid argument: ${1}" >&2
+				exit 2
+			fi
+			OFFSET=${1}
+			;;
+		*)
+			echo "Invalid argument: ${1}" >&2
+			exit 2
 			;;
 	esac
 	shift
@@ -200,7 +201,7 @@ fi
 
 declare -A PREV_VERSION=()
 # Get the previous versions from the provided pocket
-if [ -n "${POCKET}" ] && [ "${POCKET}" != "none" ] ; then
+if [ -n "${POCKET}" ] ; then
 	while read -r src version rest ; do
 		PREV_VERSION[${src}]=${version}
 	done < <(cranky rmadison -s -p "${POCKET}")
