cranky-review-sources: Add ABI positional commandline argument
Signed-off-by: Juerg Haefliger <juergh@proton.me>

diff --git a/cranky-review-sources b/cranky-review-sources
--- a/cranky-review-sources
+++ b/cranky-review-sources
@@ -39,7 +39,8 @@ function out()
 function review_src()
 {
 	local src_dir=$1
-	local cwd DEBIAN src version debdiff changes dsc prev_version prev_dsc
+	local cwd DEBIAN src version debdiff changes dsc prev_version prev_dsc \
+	      v u match
 
 	cwd=${PWD}
 
@@ -111,6 +112,15 @@ function review_src()
 			version)
 				prev_version=${PREV_VAL}
 				;;
+			abi)
+				v=${PREV_VAL%-*}
+				v=${v//./\\.}
+				u=${PREV_VAL#*-}
+				match=$(grep -m1 "^linux.* (${v}[-.]${u}\." \
+				        "${DEBIAN}"/changelog)
+				prev_version=${match#* \(}
+				prev_version=${prev_version%\) *}
+				;;
 		esac
 
 		prev_dsc="${src}"_"${prev_version}".dsc
@@ -143,7 +153,7 @@ function review_src()
 function usage()
 {
 	cat <<EOF
-Usage: cranky-review-sources [-c] [-h] [POCKET|OFFSET|VERSION]
+Usage: cranky-review-sources [-c] [-h] [POCKET|OFFSET|VERSION|ABI]
 
 Review the differences between the current kernel source packages and
 previous source packages.
@@ -153,8 +163,10 @@ Positional arguments:
   OFFSET         Get the previous package versions from the changelogs using
                  changelog entry offset OFFSET (1 == previous changelog entry).
   VERSION        Use VERSION as the previous package version.
+  ABI            Get the previous package versions from the changelogs using
+                 the newest changelog entry with abi ABI.
 
-  If neither POCKET nor OFFSET is provided, process the existing debdiff.
+  If no positional argument is provided, process the existing debdiff.
 
 Optional arguments:
   -c, --current  Only review the source package built from the current
@@ -179,7 +191,7 @@ while [ ${#} -gt 0 ] ; do
 			exit
 			;;
 		release|security|updates|proposed)
-			if [ -n "${PREV_VAL}" ] ; then
+			if [ -n "${PREV_TYPE}" ] ; then
 				echo "Invalid argument: ${1}" >&2
 				exit 2
 			fi
@@ -187,7 +199,7 @@ while [ ${#} -gt 0 ] ; do
 			PREV_VAL=${1}
 			;;
 		[1-9])
-			if [ -n "${PREV_VAL}" ] ; then
+			if [ -n "${PREV_TYPE}" ] ; then
 				echo "Invalid argument: ${1}" >&2
 				exit 2
 			fi
@@ -195,11 +207,19 @@ while [ ${#} -gt 0 ] ; do
 			PREV_VAL=${1}
 			;;
 		[1-9]*.[0-9]*.0-[0-9]*.[0-9]*)
-			if [ -n "${PREV_VAL}" ] ; then
+			if [ -n "${PREV_TYPE}" ] ; then
 				echo "Invalid argument: ${1}" >&2
 				exit 2
 			fi
 			PREV_TYPE=version
+			PREV_VAL=${1}
+			;;
+		[1-9]*.[0-9]*.0-[0-9]*)
+			if [ -n "${PREV_TYPE}" ] ; then
+				echo "Invalid argument: ${1}" >&2
+				exit 2
+			fi
+			PREV_TYPE=abi
 			PREV_VAL=${1}
 			;;
 		  *)
