cranky-update-dependents: Fix determination of latest remote tag
Signed-off-by: Juerg Haefliger <juergh@proton.me>

diff --git a/cranky-update-dependents b/cranky-update-dependents
--- a/cranky-update-dependents
+++ b/cranky-update-dependents
@@ -77,9 +77,17 @@ while IFS= read -r path ; do
 		exit 1
 	fi
 
-	tag_base=$(echo "${tag}" | \
-				   sed -e 's/_[0-9\.]*$//' -e 's/[0-9]\+\.[0-9]\+$//')
-	tag_latest=$(git tag | grep "${tag_base}" | sort -V | tail -1)
+	tag_prefix=$(echo "${tag}" | \
+					 sed -e 's/[_+][0-9\.]*$//' -e 's/[0-9]\+\.[0-9]\+$//')
+	if [ -z "${tag_prefix}" ] ; then
+		echo "Failed to parse tag ${tag}" >&2
+		exit 1
+	fi
+	tag_latest=$(git tag | grep "${tag_prefix}" | sort -V | tail -1)
+	if [ -z "${tag_latest}" ] ; then
+		echo "Failed to find latest remote tag (tag prefix: ${tag_prefix})" >&2
+		exit 1
+	fi
 
 	git clean -dxf
 	if [ ${re_run} -eq 0 ] ; then
