cranky-build-sources: Bail out if an empty pocket is provided
Signed-off-by: Juerg Haefliger <juergh@gmail.com>

diff --git a/cranky-build-sources b/cranky-build-sources
--- a/cranky-build-sources
+++ b/cranky-build-sources
@@ -111,7 +111,9 @@ fi
 
 if [ "${pocket}" != "none" ] ; then
 	# Get the previous versions from the provided pocket
+	found=0
 	while IFS=' ' read -r package version rest ; do
+		found=1
 		case "${package}" in
 			linux-meta*)
 				bo_meta+=("-v${version}")
@@ -130,6 +132,11 @@ if [ "${pocket}" != "none" ] ; then
 				exit 1
 		esac
 	done < <(cranky rmadison -s -p "${pocket}")
+fi
+
+if [ ${found} -eq 0 ] ; then
+	echo "Invalid pocket: ${pocket}" >&2
+	exit 1
 fi
 
 if [ ${#bo_meta[@]} -ne 0 ] ; then
