cranky-0: Rework commandline argument handling
Signed-off-by: Juerg Haefliger <juergh@proton.me>

diff --git a/cranky-0 b/cranky-0
--- a/cranky-0
+++ b/cranky-0
@@ -28,19 +28,12 @@ function run()
 {
 	echo
 	pr_banner "${*}"
-	"${@}"
-}
-
-function shift_ARGS()
-{
-	if [ ${#ARGS[@]} -eq 0 ] ; then
-		HELP=1
-		ARG=
-		return
+	if [ "${DRY_RUN}" -eq 1 ] ; then
+		echo "${*}"
+		echo "Skip (dry-run)"
+	else
+		"${@}"
 	fi
-
-	ARG=${ARGS[0]}
-	ARGS=("${ARGS[@]:1}")
 }
 
 function source_debian_env()
@@ -51,8 +44,7 @@ function source_debian_env()
 	fi
 }
 
-# ----------------------------------------------------------------------------
-# Subcommands
+# checkout --------------------------------------------------------------------
 
 function do_checkout()
 {
@@ -63,6 +55,8 @@ function do_checkout()
 
 	run cranky checkout "${series}":"${package}"
 }
+
+# fix -------------------------------------------------------------------------
 
 function do_fix()
 {
@@ -78,10 +72,14 @@ function do_fix()
 	run cranky fix
 }
 
+# rebase ----------------------------------------------------------------------
+
 function do_rebase()
 {
 	run cranky rebase
 }
+
+# open ------------------------------------------------------------------------
 
 function do_open()
 {
@@ -89,20 +87,37 @@ function do_open()
 	run cranky open
 }
 
+# configs ---------------------------------------------------------------------
+
 function do_configs()
 {
 	run cranky updateconfigs
 }
 
-function args_link()
-{
-	HELP_OPT_ARGS+=("[-s SRU_CYCLE]")
-}
+# link ------------------------------------------------------------------------
+
+# shellcheck disable=SC2034
+link_opt_args=(
+	"[-r]|-r, --rerun|Rerun the commands."
+	"[-s SRU_CYCLE]|-s, --sru-cycle SRU_CYCLE|SRU cycle name, e.g., 2022.05.30-1."
+)
 
 function do_link()
 {
-	run cranky link-tb "${LINK_ARGS[@]}"
+	local args
+
+	args=()
+	if [ "${RERUN}" -eq 1 ] ; then
+		args+=("-re-run")
+	fi
+	if [ -z "${SRU_CYCLE}" ] ; then
+		args+=("--sru-cycle" "${SRU_CYLE}")
+	fi
+
+	run cranky link-tb "${args[@]}"
 }
+
+# dkms ------------------------------------------------------------------------
 
 function do_dkms()
 {
@@ -111,44 +126,70 @@ function do_dkms()
 	fi
 }
 
+# close -----------------------------------------------------------------------
+
+# shellcheck disable=SC2034
+close_opt_args=(
+	"[-r]|-r, --rerun|Rerun the commands."
+)
+
 function do_close()
 {
+	local args
+
+	args=()
+	if [ "${RERUN}" -eq 1 ] ; then
+		args+=("--force")
+	fi
+
 	run cranky close
-	run cranky tag "${TAG_ARGS[@]}"
+	run cranky tag "${args[@]}"
 }
+
+# dependents ------------------------------------------------------------------
+
+# shellcheck disable=SC2034
+dependents_opt_args=(
+	"[-r]|-r, --rerun|Rerun the commands."
+)
 
 function do_dependents()
 {
-	run cranky-update-dependents "${TAG_ARGS[@]}"
+	local args
+
+	args=()
+	if [ "${RERUN}" -eq 1 ] ; then
+		args+=("--force")
+	fi
+
+	run cranky-update-dependents "${args[@]}"
 }
+
+# verify ----------------------------------------------------------------------
 
 function do_verify()
 {
 	run cranky-verify-release-ready
 }
 
-function args_build()
-{
-	if [ -z "${POCKET}" ] ; then
-		shift_ARGS
-		POCKET=${ARG}
-		HELP_POS_ARGS=("POCKET")
-	fi
-}
+# build -----------------------------------------------------------------------
+
+# shellcheck disable=SC2034
+build_pos_args=(
+	"POCKET|POCKET|Pocket containing the previous source package."
+)
 
 function do_build()
 {
 	run cranky-build-sources -f "${POCKET}"
 }
 
-function args_review()
-{
-	if [ -z "${POCKET}" ] ; then
-		shift_ARGS
-		POCKET=${ARG}
-		HELP_POS_ARGS=("POCKET")
-	fi
-}
+# review ----------------------------------------------------------------------
+
+# shellcheck disable=SC2034
+build_pos_args=(
+	"POCKET|POCKET|Pocket containing the previous source package."
+)
 
 function do_review()
 {
@@ -159,18 +200,19 @@ function do_review()
 	run review-debdiff -r | less
 }
 
-function args_cbd()
-{
-	# cbd-cli consumes all remaining arguments
-	CBD_ARGS=("${ARGS[@]}")
-	ARGS=()
-	HELP_POS_ARGS=("[CBD_ARGS]")
-}
+# cbd -------------------------------------------------------------------------
+
+# shellcheck disable=SC2034
+cbd_pos_args=(
+	"[-- CBD_ARGS...]|CBD_ARGS|Additional CBD arguments, e.g., -o amd64 -o generic."
+)
 
 function do_cbd()
 {
 	run cbd-cli build "${CBD_ARGS[@]}"
 }
+
+# push ------------------------------------------------------------------------
 
 function do_push()
 {
@@ -186,14 +228,12 @@ function do_push()
 	run cranky-push-all
 }
 
-function args_dput()
-{
-	if [ -z "${PPA}" ] ; then
-		shift_ARGS
-		PPA=${ARG}
-		HELP_POS_ARGS=("PPA")
-	fi
-}
+# dput ------------------------------------------------------------------------
+
+# shellcheck disable=SC2034
+dput_pos_args=(
+	"PPA|PPA|Build PPA."
+)
 
 function do_dput()
 {
@@ -205,79 +245,129 @@ function do_dput()
 
 function usage()
 {
-	echo -n "Usage: $(basename "${0}") [-h]"
-	if [ ${#HELP_OPT_ARGS[@]} -gt 0 ] ; then
-		printf " %s" "${HELP_OPT_ARGS[@]}"
-	fi
-	if [ ${#HELP_POS_ARGS[@]} -gt 0 ] ; then
-		printf " %s" "${HELP_POS_ARGS[@]}"
-	fi
+	echo -n "Usage: $(basename "${0}")"
+	for arg in "${OPT_ARGS[@]}" ; do
+		echo -n " ${arg%%|*}"
+	done
+	for arg in "${POS_ARGS[@]}" ; do
+		echo -n " ${arg%%|*}"
+	done
 	echo
 
-	cat <<EOF
+	echo
+	echo "Ubuntu kernel source package preparation, build, review and" \
+		 "upload helper."
+	echo
 
-Ubuntu kernel source package preparation, build, review and upload helper.
+	if [ ${#POS_ARGS[@]} -ne 0 ] ; then
+		echo "Positional arguments:"
+		for arg in "${POS_ARGS[@]}" ; do
+			arg=${arg#*|}
+			printf "  %-26s %s\n" "${arg%%|*}" "${arg#*|}"
+		done
+		echo
+	fi
 
-Positional arguments:
-  CBD_ARGS                  CBD arguments, e.g., -o amd64 -o generic.
-  POCKET                    Pocket containing the previous source package.
-  PPA                       Build PPA.
-
-Optional arguments:
-  -h, --help                Show this help text and exit.
-  -s, --sru-cycle SR_CYCLE  SRU cycle name, e.g., 2022.05.30-1.
-  -r, --rerun               Rerun 'cranky link-tb' and retag.
-EOF
+	echo "Optional arguments:"
+	for arg in "${OPT_ARGS[@]}" ; do
+		arg=${arg#*|}
+		printf "  %-26s %s\n" "${arg%%|*}" "${arg#*|}"
+	done
 }
 
 # ----------------------------------------------------------------------------
 # Main entry point
 
-# Positional subcommand arguments
-CBD_ARGS=()
-POCKET=
-PPA=
-
-# Optional subcommand arguments
-LINK_ARGS=()
-TAG_ARGS=()
-
-HELP=0
-HELP_POS_ARGS=()
-HELP_OPT_ARGS=()
-ARGS=()
+DRY_RUN=0
+help=0
+SRU_CYCLE=
+RERUN=0
 
 while [ ${#} -gt 0 ] ; do
 	case "${1}" in
+		-d|--dry-run)
+			DRY_RUN=1
+			;;
 		-h|--help)
-			HELP=1
+			help=1
 			;;
 		-s|--sru-cycle)
 			shift
-			LINK_ARGS+=("-s" "${1}")
+			SRU_CYCLE=${1}
 			;;
 		-r|--rerun)
-			LINK_ARGS+=("-r")
-			TAG_ARGS+=("-f")
+			RERUN=1
+			;;
+		--)
+			shift
+			break
+			;;
+		-*)
+			echo "Invalid argumennt: ${1}" >&2
+			exit 2
 			;;
 		*)
-			ARGS=("${@}")
 			break
 			;;
 	esac
 	shift
 done
 
-readarray -t CMDS < <(echo "${0##*--}" | tr "-" "\n")
+# Collect the commands from the link name
+readarray -t cmds < <(echo "${0##*--}" | tr "-" "\n")
 
-# Parse the provided commandline arguments
-for cmd in "${CMDS[@]}" ; do
-	if [ "$(type -t args_"${cmd}")" = "function" ]; then
-		args_"${cmd}"
-	fi
+OPT_ARGS=(
+	"[-d]|-d, --dry run|"
+	"[-h]|-h, --help|Show this help text and exit."
+)
+
+POS_ARGS=()
+
+# Collect the optional and positional arguments for the selected commands
+for cmd in "${cmds[@]}" ; do
+	# shellcheck disable=SC2178
+	declare -n args=${cmd}_opt_args
+	OPT_ARGS+=("${args[@]}")
+
+	# shellcheck disable=SC2178
+	declare -n args=${cmd}_pos_args
+	POS_ARGS+=("${args[@]}")
 done
 
-if [ ${#ARGS[@]} -ne 0 ] || [ ${HELP} -eq 1 ] ; then
+# Sort the optional arguments and weed out duplicates
+readarray -t OPT_ARGS < <(printf "%s\n" "${OPT_ARGS[@]}" | sort -u)
+
+# Process the positional arguments
+for arg in "${POS_ARGS[@]}" ; do
+	case "${arg%%|*}" in
+		POCKET)
+			if [ ${#} -eq 0 ] ; then
+				usage
+				exit 2
+			fi
+			POCKET=${1}
+			;;
+		PPA)
+			if [ ${#} -eq 0 ] ; then
+				usage
+				exit 2
+			fi
+			PPA=${1}
+			;;
+		"[-- CBD_ARGS...]")
+			CBD_ARGS=("${@}")
+			while [ ${#} -gt 0 ] ; do shift ; done
+			break
+			;;
+		*)
+			echo "Unsupported argument name: ${arg}" >&2
+			exit 1
+			;;
+	esac
+	shift
+done
+
+if [ ${#} -gt 0 ] || [ ${help} -eq 1 ] ; then
 	usage
 	exit 2
 fi
@@ -285,6 +375,6 @@ fi
 trap out EXIT INT TERM HUP
 
 # Run the command(s)
-for cmd in "${CMDS[@]}" ; do
+for cmd in "${cmds[@]}" ; do
 	do_"${cmd}"
 done
