cranky-build-sources: Be more verbose
Signed-off-by: Juerg Haefliger <juergh@proton.me>

diff --git a/cranky-build-sources b/cranky-build-sources
--- a/cranky-build-sources
+++ b/cranky-build-sources
@@ -205,7 +205,7 @@ else
 		fi
 
 		if [ -z "${package}" ] || [ -z "${version}" ] ; then
-			echo "Failed to determine package and/or version" >&2
+			echo "Failed to determine package and/or version in ${path}" >&2
 			exit 1
 		fi
 
