cranky-2--link-close-deps-verify: Add commandline options
Signed-off-by: Juerg Haefliger <juergh@proton.me>

diff --git a/cranky-2--link-close-deps-verify b/cranky-2--link-close-deps-verify
--- a/cranky-2--link-close-deps-verify
+++ b/cranky-2--link-close-deps-verify
@@ -1,6 +1,33 @@
 #!/bin/bash -eu
 
-cranky link-tb
+function usage()
+{
+	cat <<EOF
+Usage: $(basename "${0}") [-h] [-s SRU_CYCLE]
+EOF
+}
+
+link_tb=()
+
+while [ ${#} -gt 0 ] ; do
+	case "${1}" in
+		-h|--help)
+			usage
+			exit
+			;;
+		-s|--sru-cylce)
+			shift
+			link_tb+=("-s" "${1}")
+			;;
+		*)
+			echo "Invalid argument: ${1}" >&2
+			exit 2
+			;;
+	esac
+	shift
+done
+
+cranky link-tb "${link_tb[@]}"
 ./update-dkms-versions
 cranky close
 cranky tag
