dump-guest: Use 'virsh dump' to dumpt a libvirt guest
... rather than using a monitor command. Virsh has no gained the
capability of dumping memory only, so use it.

Also do some cleanups and restructuring to make things simpler.

Signed-off-by: Juerg Haefliger <juergh@gmail.com>

diff --git a/dump-guest b/dump-guest
--- a/dump-guest
+++ b/dump-guest
@@ -3,33 +3,21 @@
 # Dump the memory of a libivrt or QEMU guest
 #
 
-function cleanup()
-{
-	trap - EXIT TERM INT
-
-	if [ -e "${TMPFILE}" ] ; then
-		if [ -r "${TMPFILE}" ] ; then
-			rm "${TMPFILE}"
-		else
-			sudo rm "${TMPFILE}"
-		fi
-	fi
-}
-
 function usage()
 {
 	cat <<EOF
-Usage: dump-guest [options] [<dumpfile>]
+Usage: dump-guest -d DOMAIN | -s SOCKET [-h] [DUMP_FILE]
 
 Dump the memory of a libvirt/QEMU guest for analysis with crash.
 
-Options:
-  -d, --domain <DOMAIN>   Dump libvirt guest domamin <DOMAIN>
-  -s, --socket <SOCKET>   Dump QEMU guest with QEMU monitor socket <SOCKET>
+Opional arguments:
+  -d, --domain DOMAIN  Dump libvirt guest domamin DOMAIN.
+  -h, --help           Show this help text and exit.
+  -s, --socket SOCKET  Dump QEMU guest with QEMU monitor socket SOCKET.
 EOF
 }
 
-dump=
+dump_file=
 domain=
 socket=
 
@@ -37,47 +25,56 @@ while [ $# -ne 0 ] ; do
 	case "${1}" in
 		-d|--domain)
 			shift
-			socket=${1}
+			domain=${1}
+			;;
+		-h|--help)
+			usage
+			exit
 			;;
 		-s|--socket)
 			shift
 			socket=${1}
 			;;
 		*)
-			if [ -n "${dump}" ] ; then
+			if [ -n "${dump_file}" ] ; then
 				echo "Invalid argument: ${1}"
 				exit 2
 			fi
-			dump=${1}
+			dump_file=${1}
 			;;
 	esac
 	shift
 done
 
-dump=${dump:-dump.$(date +'%Y%m%d%H%M')}
-
-TMPFILE=$(mktemp -u /tmp/dump-guest.XXXXXX)
-trap cleanup EXIT TERM INT 
-
-if [ -n "${domain}" ] ; then
-	virsh qemu-monitor-command ${domain} --hmp \
-		  --cmd "dump-guest-memory -z ${TMPFILE}"
-
-elif [ -n "${socket}" ] ; then
-	echo "dump-guest-memory -z ${TMPFILE}" | socat - UNIX-CONNECT:"${socket}"
-
-else
-	echo "Must specify either --socket or --domain"
+if [ -z "${domain}" ] && [ -z "${socket}" ] ; then
+	usage
 	exit 2
 fi
 
-if [ -r "${TMPFILE}" ] ; then
-	mv "${TMPFILE}" "${dump}"
-elif [ -e "${TMPFILE}" ] ; then
-	uid=$(id -un)
-	gid=$(id -gn)
-	sudo chown "${uid}:${gid}" "${TMPFILE}"
-	mv "${TMPFILE}" "${dump}"
+dump_file=${dump_file:-dump.$(date +'%Y%m%d%H%M')}
+
+tmpf=$(mktemp -u --tmpdir dump-guest.XXXXXX)
+# shellcheck disable=SC2064
+trap "sudo rm -f ${tmpf}" EXIT INT TERM HUP
+
+if [ -n "${domain}" ] ; then
+	#	virsh qemu-monitor-command "${domain}" --hmp \
+	#		  --cmd dump-guest-memory -z "${tmpf}"
+	virsh dump "${domain}" "${tmpf}" --memory-only --format=kdump-zlib
+elif [ -n "${socket}" ] ; then
+	echo "dump-guest-memory -z ${tmpf}" | socat - UNIX-CONNECT:"${socket}"
 fi
 
-echo "Created dumpfile ${dump}"
+if ! [ -f "${tmpf}" ] ; then
+	echo "Failed to dump guest"
+	exit 1
+fi
+
+# Just in case
+sudo chown "$(id -un):$(id -gn)" "${tmpf}"
+chmod 644 "${tmpf}"
+
+# Move the dumpfile
+mv "${tmpf}" "${dump_file}"
+
+echo "Created dumpfile ${dump_file}"
