find-linux-fixes: Replace --smart with --dir DIR
Provide an alternate repo directory rather than assuming that the script is
run inside a valid git repo directory.

Signed-off-by: Juerg Haefliger <juergh@gmail.com>

diff --git a/find-linux-fixes b/find-linux-fixes
--- a/find-linux-fixes
+++ b/find-linux-fixes
@@ -22,7 +22,7 @@ function find_fixes()
 
 function find_upstream_ref()
 {
-	local commit=${1}
+	local path=${1} commit=${2}
     local pattern_list pattern found
 
     pattern_list=(
@@ -34,7 +34,7 @@ function find_upstream_ref()
     pattern=$(printf "|%s" "${pattern_list[@]}")
     pattern=${pattern:1}
 
-    found=$(git log --format="%b" "${commit}" -1 | \
+    found=$(git -C "${path}" log --format="%b" "${commit}" -1 | \
                 grep -iP "${pattern}" | \
                 grep -oP '[0-9a-f]{12,}' | head -1 | tr -d '\n' || true)
 
@@ -44,19 +44,21 @@ function find_upstream_ref()
 function usage()
 {
 	cat <<EOF
-Usage: find-linux-fixes [-h] [-s] COMMIT [COMMIT ...]
+Usage: find-linux-fixes [-h] [-d DIR] COMMIT [COMMIT ...]
 
-Find 'Fixes:' commits in the main Linux repo for the specified COMMIT.
+Find 'Fixes:' commits in the main Linux repo (Linus' repo) for the specified
+COMMIT(s).
 
 Optional arguments:
-  -h, --help   Show this help text and exit.
-  -s, --smart  If a provided commit is not found in Linus' repo, parse its
-               commit message for a reference to the original upstream
-               commit and if found, find 'Fixes:' commits for that commit hash.
+  -h, --help     Show this help text and exit.
+  -d, --dir DIR  If a provided commit is not found in Linus' repo, try to look it
+                 up in <DIR> and parse its commit message for a reference to the
+                 original upstream commit. If found, find 'Fixes:' commits for
+                 that upstream commit.
 EOF
 }
 
-smart=0
+path=
 commits=()
 
 while [ $# -gt 0 ] ; do
@@ -65,8 +67,9 @@ while [ $# -gt 0 ] ; do
             usage
             exit
             ;;
-		-s|--smart)
-			smart=1
+		-d|--dir)
+			shift
+			path=${1}
 			;;
         -*)
             echo "Unexpected argument: ${1}" 1>&2
@@ -80,36 +83,52 @@ while [ $# -gt 0 ] ; do
     shift
 done
 
+# Verify that path is a valid git repo
+if [ -n "${path}" ] && \
+   ! git -C "${path}" rev-parse --inside-work-tree >/dev/null 2>&1 ; then
+	echo "Error: ${path} is not a valid git repo"
+	exit
+fi
+
 for commit in "${commits[@]}" ; do
-	# Check that the commit exists in Linus' repo
+	# Get the commit subject from Linus' repo
 	linus=$(git --git-dir="${LINUX_REPO}" log --format='%h ("%s")' \
 				"${commit}" -1 2>/dev/null || true)
+
 	if [ -z "${linus}" ] ; then
-		if [ "${smart}" -eq 0 ] ; then
+		if [ -z "${path}" ] ; then
 			echo "Error: Commit ${commit} not found in Linus' repo"
 			continue
 		fi
 
-		# Try to find an upstream commit reference in the commit message
-		upstream=$(find_upstream_ref "${commit}")
-		if [ -z "${upstream}" ] ; then
-			echo "Error: Commit ${commit} not found in Linus' repo and" \
-				 "doesn't contain an upstream reference"
+		# Check if the commit exists in the provided repo
+		if ! git -C "${path}" cat-file -e "${commit}^{commit}" 2>/dev/null ; then
+			echo "Error: Commit ${commit} not found in Linus' repo nor in" \
+				 "'${path}'"
 			continue
 		fi
 
-		# Check that that upstream commit reference exists in Linus' repo
+		# Try to find an upstream commit reference in the commit message
+		upstream=$(find_upstream_ref "${path}" "${commit}")
+		if [ -z "${upstream}" ] ; then
+			echo "Error: Commit ${commit} found in '${path}' but doesn't" \
+				 "contain an upstream reference"
+			continue
+		fi
+
+		# Get the subject of the upstream commit from Linus' repo
 		linus=$(git --git-dir="${LINUX_REPO}" log --format='%h ("%s")' \
 					"${upstream}" -1 2>/dev/null || true)
 		if [ -z "${linus}" ] ; then
-			echo "Error: Commit ${commit} not found in Linus' repo but" \
-				 "contains an upstream reference (${commit::12}) which is" \
-				 "also not found in Linus' repo"
+			echo "Error: Commit ${commit} found in '${path}' and contains" \
+				 "an upstream reference (${upstream::12}) which is not found" \
+				 "in Linus' repo"
 			continue
 		fi
 
 		# Make it clear that we're processing a different commit
 		linus="${commit::12} -> [upstream] ${linus}"
+		commit=${upstream}
 	fi
 
 	echo "${linus}"
