genmasterconfigs: Add 'set +e' in exit handler
Signed-off-by: Juerg Haefliger <juergh@gmail.com>

diff --git a/genmasterconfigs b/genmasterconfigs
--- a/genmasterconfigs
+++ b/genmasterconfigs
@@ -7,6 +7,7 @@ function out()
 {
 	local rc=${?}
 
+	set +e
 	trap - EXIT INT TERM HUP
 
 	if [ "${BRANCHED}" -eq 1 ] ; then
@@ -24,14 +25,14 @@ function out()
 	fi
 
 	if [ ${rc} -ne 0 ] ; then
-		echo "-- Script failed" >&2
+		echo "-- Error: Script failed" >&2
 	fi
 
 	exit "${rc}"
 }
 
 if ! [ -f debian/debian.env ] ; then
-	echo "-- Not an Ubuntu kernel tree" >&2
+	echo "-- Error: Not an Ubuntu kernel tree" >&2
 	exit 1
 fi
 
@@ -66,4 +67,6 @@ fi
 
 echo "-- Create configs"
 cranky fdr clean genconfigs
+
+rm -rf MASTERCONFIGS
 mv CONFIGS MASTERCONFIGS
