make-kernel: Add support for building kernels the 'Ubuntu-way'
Signed-off-by: Juerg Haefliger <juergh@gmail.com>

diff --git a/make-kernel b/make-kernel
--- a/make-kernel
+++ b/make-kernel
@@ -4,66 +4,239 @@
 #
 
 
-function get_series()
+function run_in_schroot()
 {
-	local series version patchlevel
+	# FIXME: Silence chroot warnings
+	export LANG=
+	export LC_TIME=POSIX
+	export LC_MONETARY=POSIX
+	export LC_COLLATE=POSIX
+	export LC_ADDRESS=POSIX
+	export LC_TELEPHONE=POSIX
+	export LC_NAME=POSIX
+	export LC_MEASUREMENT=POSIX
+	export LC_IDENTIFICATION=POSIX
+	export LC_NUMERIC=POSIX
+	export LC_PAPER=POSIX
 
-	if [ -e debian/debian.env ] ; then
-		# shellcheck disable=SC1091
-		. debian/debian.env
-		series=$(dpkg-parsechangelog -l "${DEBIAN}/changelog" -S Distribution)
-		if [ "${series}" = "UNRELEASED" ] ; then
-			series=$(dpkg-parsechangelog -l "${DEBIAN}/changelog" \
-										 -S Distribution -o 1 -c 1)
+	echo
+	echo "+++ Running in '${SCHROOT}': ${*}"
+	echo
+
+	if [ "${DRY_RUN}" -eq 0 ] ; then
+		schroot -c "${SCHROOT}" -- "${@}"
+	fi
+}
+
+
+function print_vars()
+{
+	local var
+
+	for var in "${@}" ; do
+		if [[ "$(declare -p "${var}" 2>/dev/null)" =~ "declare -a" ]] ; then
+			arr="${var}[@]"
+			val=${!arr:-}
+		else
+			val=${!var:-}
 		fi
+		printf "%-13s : %s\n" "${var}" "${val}"
+	done
+}
 
-	else
-		version=$(awk '/^VERSION = / { print $3 ; exit }' Makefile)
-		patchlevel=$(awk '/^PATCHLEVEL = / { print $3 ; exit }' Makefile)
 
-		# The schroot distro, based on the kernel version
-		case "${version}.${patchlevel}" in
-			3.[0-9])
-				# 3.0 to 3.9
-				series=precise
-				;;
-			3.[1-9][0-9])
-				# 3.10 to 3.99
-				series=trusty
-				;;
-			4.[0-9])
-				# 4.0 to 4.9
-				series=xenial
-				;;
-			*)
-				series=bionic
-				;;
-		esac
+function need_cross_compilation()
+{
+	local schroot_arch
+
+	schroot_arch=${SCHROOT#*-}
+
+	# Need to cross compile if the schroot and the deb architectures differ
+	# unless we're building an i386 kernel in an amd64 schroot
+	[ "${schroot_arch}" != "${DEB_ARCH}" ] && \
+		! ( [ "${schroot_arch}" = "amd64" ] && [ "${DEB_ARCH}" = "i386" ] )
+}
+
+
+function get_upstream_schroot()
+{
+	local version patchlevel series
+
+	version=$(awk '/^VERSION = / { print $3 ; exit }' Makefile)
+	patchlevel=$(awk '/^PATCHLEVEL = / { print $3 ; exit }' Makefile)
+
+	# The schroot distro, based on the kernel version
+	case "${version}.${patchlevel}" in
+		3.[0-9])
+			# 3.0 to 3.9
+			series=precise
+			;;
+		3.[1-9][0-9])
+			# 3.10 to 3.99
+			series=trusty
+			;;
+		4.[0-9])
+			# 4.0 to 4.9
+			series=xenial
+			;;
+		*)
+			series=bionic
+			;;
+	esac
+
+	echo "${series}-amd64"
+}
+
+
+function build_upstream_kernel()
+{
+	local arch target buildd found
+
+	# Use the default schroot
+	SCHROOT=${SCHROOT:-$(get_upstream_schroot)}
+
+	# The kernel build architecture and default target
+	case "${DEB_ARCH}" in
+		arm64)
+			arch=arm64
+			target=Image.gz
+			;;
+		amd64|i386)
+			arch=x86
+			target=bzImage
+			;;
+		powerpc)
+			arch=powerpc
+			target=zImage
+			;;
+		ppc64el)
+			arch=powerpc
+			target=vmlinux
+			;;
+		*)
+			echo "+++ Error: Unsupported arch: ${DEB_ARCH}"
+			exit 1
+			;;
+	esac
+
+	# Use the default target
+	if [ ${#TARGET[@]} -eq 0 ] ; then
+		TARGET=("${target}")
 	fi
 
-	echo "${series}"
+	# Exports for cross-compilation (doing this here only works if the schroots
+	# are configured to preserve the environment)
+	if need_cross_compilation ; then
+		# shellcheck disable=SC2046
+		export $(dpkg-architecture -a "${DEB_ARCH}" 2>/dev/null)
+		export CROSS_COMPILE=${DEB_HOST_GNU_TYPE}-
+		export ARCH=${arch}
+	fi
+
+	# Create the out-of-tree build directory and copy the config file
+	buildd="build/${DEB_ARCH}"
+	if ! [ -d "${buildd}" ] ; then
+		mkdir -p "${buildd}"
+	fi
+	cp "${CONFIG}" "${buildd}/.config"
+
+	# We're building out-of-tree so squirrel away .config or make will complain
+	# about a tainted source
+	if [ -e .config ] ; then
+		mv .config .config.squirrel
+		trap "mv .config.squirrel .config" EXIT INT TERM HUP
+	fi
+
+	# Number of parallel gcc build jobs
+	found=0
+	for arg in "${ARGS[@]}" ; do
+		if [ "${arg#-j}" != "${arg}" ] ; then
+			found=1
+			break
+		fi
+	done
+	if [ ${found} -eq 0 ] ; then
+		ARGS+=("-j$(getconf _NPROCESSORS_ONLN)")
+	fi
+
+	# Print interesting variables
+	print_vars SCHROOT DEB_ARCH TARGET ARCH CROSS_COMPILE ARGS
+
+	# Finally kick off the build
+	run_in_schroot make "${TARGET[@]}" O="${buildd}" "${ARGS[@]}"
+}
+
+
+function get_ubuntu_schroot()
+{
+	local series
+
+	# shellcheck disable=SC1091
+	. debian/debian.env
+	series=$(dpkg-parsechangelog -l "${DEBIAN}/changelog" -S Distribution)
+	if [ "${series}" = "UNRELEASED" ] ; then
+		series=$(dpkg-parsechangelog -l "${DEBIAN}/changelog" \
+									 -S Distribution -o 1 -c 1)
+	fi
+
+	if [ "${series}" = "precise" ] && [ "${DEB_ARCH}" = "powerpc" ] ; then
+		# Can't do powerpc cross-compilation in a Precise schroot
+		echo "${series}-powerpc"
+	else
+		echo "${series}-amd64"
+	fi
+}
+
+
+function build_ubuntu_kernel()
+{
+	# Use the default schroot if unspecified
+	SCHROOT=${SCHROOT:-$(get_ubuntu_schroot)}
+
+	# Use the default target if unspecified
+	if [ ${#TARGET[@]} -eq 0 ] ; then
+		TARGET=("clean" "build")
+	fi
+
+	# Exports for cross-compilation (doing this here only works if the schroots
+	# are configured to preserve the environment)
+	if need_cross_compilation ; then
+		# shellcheck disable=SC2046
+		export $(dpkg-architecture -a "${DEB_ARCH}" 2>/dev/null)
+		export CROSS_COMPILE=${DEB_HOST_GNU_TYPE}-
+	fi
+
+	# Print interesting variables
+	print_vars SCHROOT DEB_ARCH TARGET CROSS_COMPILE
+
+	# Finally kick off the build
+	run_in_schroot fakeroot debian/rules "${TARGET[@]}"
 }
 
 
 function usage()
 {
 	cat << EOF
-Usage: make-kernel [-a ARCH] [-c CONFIG] [-d] [-h] [-s SCHROOT] [TARGET]
-                   [-- MAKE_OPTS]
+Usage: make-kernel [-a ARCH] [-d] [-h] [-s SCHROOT] [-u] [TARGET [TARGET]...]
+       make-kernel [-a ARCH] [-c CONFIG] [-d] [-h] [-s SCHROOT]
+                   [TARGET [TARGET]...] [-- MAKE_OPTS]
 
-Build a kernel in a chroot.
+Build an upstream or Ubuntu kernel in a schroot.
 
-TARGET     The build target. If not specified, defaults to the kernel build
-           target for the selected architecture (for example 'bzImage' for
-           amd64).
-MAKE_OPTS  Additional options that are passed to the kernel's Makefile.
+Postinal arguments:
+  TARGET     The (list of) build target(s). If not specified, defaults to the
+             kernel build target for the selected architecture (for example
+             'bzImage' for amd64) or to the 'clean build' targets when building
+             an Ubuntu kernel.
+  MAKE_OPTS  Additional options that are passed to the kernel's Makefile.
 
-Available options:
-  -a, --arch ARCH         Build kernel for arch ARCH
-  -c, --config CONFIG     Use config file CONFIG instead of .config
-  -d, --dry-run           Only show the command to be executed without doing so
-  -h, --help              Show this help text
-  -h, --schroot SCHROOT   Which schroot to use for the compilation
+Optional arguments:
+  -a, --arch ARCH         Build kernel for architecture ARCH.
+  -c, --config CONFIG     Use config file CONFIG instead of .config.
+  -d, --dry-run           Show the build command but don't execute it.
+  -h, --help              Show this help text.
+  -s, --schroot SCHROOT   Use schroot SCHROOT for the build.
+  -u, --ubuntu            Build an Ubuntu kernel.
 EOF
 	exit 2
 }
@@ -72,34 +245,40 @@ EOF
 # -----------------------------------------------------------------------------
 # Parse the commandline
 
-arch=$(dpkg-architecture -q DEB_HOST_ARCH)
-config=.config
-dry_run=0
-schroot=
-target=
+DEB_ARCH=$(dpkg-architecture -q DEB_HOST_ARCH)
+CONFIG=.config
+DRY_RUN=0
+SCHROOT=
+TARGET=()
+UBUNTU=0
+ARGS=()
 
 while [ $# -gt 0 ] ; do
 	case "${1}" in
 		-a|--arch)
 			shift
-			arch=${1}
+			DEB_ARCH=${1}
 			;;
 		-c|--config)
 			shift
-			config=${1}
+			CONFIG=${1}
 			;;
 		-d|--dry-run)
-			dry_run=1
+			DRY_RUN=1
 			;;
 		-h|--help)
 			usage
 			;;
 		-s|--schroot)
 			shift
-			schroot=${1}
+			SCHROOT=${1}
+			;;
+		-u|--ubuntu)
+			UBUNTU=1
 			;;
 		--)
 			shift
+			ARGS=("${@}")
 			break
 			;;
 		-*)
@@ -107,126 +286,18 @@ while [ $# -gt 0 ] ; do
 			exit 1
 			;;
 		*)
-			if [ -n "${target}" ] ; then
-				echo "Error: Unexpected argument: ${1}"
-				exit 1
-			fi
-			target=${1}
+			TARGET+=("${1}")
 			;;
 	esac
 	shift
 done
 
-# The build architecture and target
-case "${arch}" in
-	arm64)
-		ARCH=arm64
-		target=${target:-Image.gz}
-		;;
-	amd64|i386)
-		ARCH=x86
-		target=${target:-bzImage}
-		;;
-	powerpc)
-		ARCH=powerpc
-		target=${target:-zImage}
-		;;
-	ppc64el)
-		ARCH=powerpc
-		target=${target:-vmlinux}
-		;;
-	*)
-		echo "Error: Unsupported arch: ${arch}"
+if [ ${UBUNTU} -eq 1 ] ; then
+	build_ubuntu_kernel
+else
+	if ! [ -e "${CONFIG}" ] ; then
+		echo "+++ Error: Config file not found: ${CONFIG}"
 		exit 1
-		;;
-esac
-
-
-# -----------------------------------------------------------------------------
-# Check for the Makefile and the config file
-
-if ! [ -e Makefile ] ; then
-	echo "Error: No such file: Makefile"
-	exit 1
-fi
-
-if ! [ -e "${config}" ] ; then
-	echo "Error: No such file: ${config}"
-	exit 1
-fi
-
-# Create the build directory and copy the config file
-tarch=$(grep -m1 '# Linux/' "${config}" | sed -e 's,# Linux/,,' -e 's, .*,,')
-buildd="build/${tarch}"
-if ! [ -d "${buildd}" ] ; then
-	mkdir -p "${buildd}"
-fi
-cp "${config}" "${buildd}/.config"
-
-# Determine which schroot to use for the compilation
-if [ -z "${schroot}" ] ; then
-	series=$(get_series)
-
-	# FIXME: RHEL special case
-	if grep -q 'RH_KABI' "${config}" ; then
-		schroot=centos7-x86_64
-	else
-		schroot="${series}-amd64"
 	fi
-fi
-
-
-# -----------------------------------------------------------------------------
-# Assemble the make env and options
-
-# Number of parallel gcc build jobs
-numjobs="-j$(getconf _NPROCESSORS_ONLN)"
-for arg in "${@}" ; do
-	if [ "${arg#-j}" != "${arg}" ] ; then
-		numjobs=
-		break
-	fi
-done
-
-# Are we cross compiling?
-CROSS_COMPILE=
-if [ "${arch}" != "$(dpkg-architecture -q DEB_HOST_ARCH)" ] && \
-   ! ( [ "${arch}" = "i386" ] && \
-	   [ "$(dpkg-architecture -q DEB_HOST_ARCH)" = "amd64" ] ) ; then
-	CROSS_COMPILE=$(dpkg-architecture -a "${arch}" -q DEB_HOST_GNU_TYPE)-
-fi
-export ARCH CROSS_COMPILE
-
-# FIXME: Silence chroot warnings
-export LANG=
-export LC_TIME=POSIX
-export LC_MONETARY=POSIX
-export LC_COLLATE=POSIX
-export LC_ADDRESS=POSIX
-export LC_TELEPHONE=POSIX
-export LC_NAME=POSIX
-export LC_MEASUREMENT=POSIX
-export LC_IDENTIFICATION=POSIX
-export LC_NUMERIC=POSIX
-export LC_PAPER=POSIX
-
-echo "ARCH:            ${ARCH}"
-echo "CROSS_COMPILE:   ${CROSS_COMPILE}"
-echo "schroot:         ${schroot}"
-echo "target:          ${target}"
-echo "config:          ${config}"
-echo "build directory: ${buildd}"
-echo
-
-# Squirrel away .config or make will complain about a tainted source
-if [ -e .config ] ; then
-	mv .config .config.squirrel
-	trap "mv .config.squirrel .config" EXIT INT TERM HUP
-fi
-
-echo "schroot -c ${schroot} -- make oldnoconfig ${target} ${numjobs}" \
-	 "O=${buildd} ${@} 2>&1 | tee ${buildd}/build.log"
-if [ "${dry_run}" -eq 0 ] ; then
-	schroot -c "${schroot}" -- make oldnoconfig "${target}" ${numjobs} \
-			O="${buildd}" "${@}" 2>&1 | tee "${buildd}/build.log"
+	build_upstream_kernel
 fi
