sec-find-cve: Print not founds
Signed-off-by: Juerg Haefliger <juergh@proton.me>

diff --git a/sec-find-cve b/sec-find-cve
--- a/sec-find-cve
+++ b/sec-find-cve
@@ -6,8 +6,10 @@
 cve=${1}
 
 while IFS= read -r branch ; do
-	match=$(git log --oneline --grep "${cve}$" --max-count=1 "${branch}~1000..${branch}")
+	match=$(git log --oneline --grep "${cve}$" --max-count=1 "${branch}" -50000 || true)
 	if [ -n "${match}" ] ; then
 		printf "%-27s -- %s -- %s\n" "${branch}" "${cve}" "${match}"
+	else
+		printf "%-27s -- %s -- %s\n" "${branch}" "${cve}" "Not found"
 	fi
 done < <(git branch -r | sed 's/^..//' | grep '^linux-ubuntu/.*/linux$')
